<?xml version="1.0"?>
<package format="3">
  <name>dug_vision</name>
  <version>1.0.0</version>
  <description>Edge-AI visual target detection for DUG</description>
  <maintainer email="bahat@example.com">Bahattin Yunus</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>dug_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
