<?xml version="1.0"?>
<package format="3">
  <name>dug_core</name>
  <version>1.0.0</version>
  <description>Core autonomy logic for DUG</description>
  <maintainer email="bahat@example.com">Bahattin Yunus</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
